# Generated by Django 4.2.16 on 2024-09-22 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('instagaram_address', models.CharField(blank=True, max_length=30, null=True)),
                ('working_days', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'SATURDAY'), ('2', 'SUNDAY'), ('3', 'MONDAY'), ('4', 'TUESDAY'), ('5', 'WEDNESDAY'), ('6', 'THURSDAY'), ('7', 'FRIDAY')], max_length=13)),
                ('working_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_service', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='services-image/')),
                ('active', models.BooleanField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('created_add', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('image', models.ImageField(upload_to='barbers-image/')),
                ('active', models.BooleanField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('services', models.ManyToManyField(to='barbers.service')),
            ],
        ),
    ]
