# Generated by Django 4.2.16 on 2024-09-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_barbershop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
