# Generated by Django 4.2.16 on 2024-09-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_barbershop_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberShopImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='shop-image/')),
            ],
        ),
        migrations.AlterField(
            model_name='barber',
            name='services',
            field=models.ManyToManyField(related_name='barber', to='barbers.service'),
        ),
    ]
