# Generated by Django 4.2.16 on 2024-09-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0004_barbershopimage_alter_barber_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='image',
            field=models.ManyToManyField(related_name='barbershop', to='barbers.barbershopimage'),
        ),
    ]
