# Generated by Django 4.2.16 on 2024-09-24 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0006_rename_image_barbershop_images_servicecomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbercomment',
            name='services',
        ),
        migrations.RemoveField(
            model_name='servicecomment',
            name='services',
        ),
        migrations.AddField(
            model_name='barbercomment',
            name='barber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='barber_comment', to='barbers.barber'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecomment',
            name='service',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='service_comment', to='barbers.service'),
            preserve_default=False,
        ),
    ]
