# Generated by Django 4.2.16 on 2024-10-04 11:48

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0007_remove_barbercomment_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbercomment',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barber_comment', to='barbers.barber', verbose_name='barber'),
        ),
        migrations.AlterField(
            model_name='barbercomment',
            name='stars',
            field=models.CharField(choices=[('1', 'Awful'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'Perfect')], max_length=1, verbose_name='stars'),
        ),
        migrations.AlterField(
            model_name='barbercomment',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='address',
            field=models.CharField(max_length=100, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='working_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'SATURDAY'), ('2', 'SUNDAY'), ('3', 'MONDAY'), ('4', 'TUESDAY'), ('5', 'WEDNESDAY'), ('6', 'THURSDAY'), ('7', 'FRIDAY')], max_length=13, verbose_name='working_days'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='working_time',
            field=models.CharField(max_length=100, verbose_name='working_time'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='servicecomment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_comment', to='barbers.service', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='servicecomment',
            name='stars',
            field=models.CharField(choices=[('1', 'Awful'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'Perfect')], max_length=1, verbose_name='stars'),
        ),
        migrations.AlterField(
            model_name='servicecomment',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
    ]
